export const PATHS = {
  home: '/',
  boards: '/boards',
  search: '/search',
  articles: 'articles',
  articleDetails: '/articles/:id',
  articleDetailsMetadata: '/articles/:id/metadata/:type',
  articleDetailsPreview: '/articles/:id/preview',
  articleDetailsNotice: '/articles/:id/notice',
  articleDetailsDownload: '/articles/:id/download',
  articlesAccepted: 'articles-accepted',
  authors: '/authors',
  volumes: '/volumes',
  volumeDetails: '/volumes/:id',
  sections: '/sections',
  sectionDetails: '/sections/:id',
  about: '/about',
  acknowledgements: '/acknowledgements',
  indexation: '/indexing',
  credits: '/credits',
  accessibility: '/accessibility',
  news: '/news',
  statistics: '/statistics',
  publish: '/publish',
  forAuthors: '/for-authors',
  ethicalCharter: '/ethical-charter',
  forReviewers: '/for-reviewers',
  forConferenceOrganisers: '/for-conference-organisers',
  notFound: '*',
};

export type PathKeys = keyof typeof PATHS;
