name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - dev-ccsd
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Define secrets and load configuration file path dynamically
      - name: Set secrets and config file path
        id: config_setup
        run: |
          echo "VITE_API_ROOT_ENDPOINT=${{ secrets.VITE_API_ROOT_ENDPOINT }}" >> $GITHUB_ENV
          echo "VITE_JOURNAL_RVCODE=${{ secrets.VITE_JOURNAL_RVCODE }}" >> $GITHUB_ENV
          echo "CONFIG_FILE=journal.${{ secrets.VITE_JOURNAL_RVCODE }}.yaml" >> $GITHUB_ENV

      # Check if dynamic config file exists
      - name: Check for configuration file
        id: config_exists
        run: |
          if [ -f "$CONFIG_FILE" ]; then
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "file_exists=false" >> $GITHUB_ENV
          fi

      # Load configuration from file if exists, or use defaults
      - name: Load or fallback to defaults
        run: |
          if [ "$file_exists" = "true" ]; then
            CONFIG_VALUES=$(cat "$CONFIG_FILE" | yq eval -j -)

            export VITE_JOURNAL_PRIMARY_COLOR=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_PRIMARY_COLOR // "#7A020D"')
            export VITE_JOURNAL_PRIMARY_TEXT_COLOR=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_PRIMARY_TEXT_COLOR // "#ffffff"')
            export VITE_JOURNAL_HOMEPAGE_LATEST_ARTICLES_CAROUSEL_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_HOMEPAGE_LATEST_ARTICLES_CAROUSEL_RENDER // "true"')
            export VITE_JOURNAL_HOMEPAGE_LATEST_NEWS_CAROUSEL_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_HOMEPAGE_LATEST_NEWS_CAROUSEL_RENDER // "true"')
            export VITE_JOURNAL_HOMEPAGE_MEMBERS_CAROUSEL_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_HOMEPAGE_MEMBERS_CAROUSEL_RENDER // "true"')
            export VITE_JOURNAL_HOMEPAGE_STATS_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_HOMEPAGE_STATS_RENDER // "true"')
            export VITE_JOURNAL_HOMEPAGE_JOURNAL_INDEXATION_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_HOMEPAGE_JOURNAL_INDEXATION_RENDER // "true"')
            export VITE_JOURNAL_HOMEPAGE_SPECIAL_ISSUES_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_HOMEPAGE_SPECIAL_ISSUES_RENDER // "true"')
            export VITE_JOURNAL_HOMEPAGE_LATEST_ACCEPTED_ARTICLES_CAROUSEL_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_HOMEPAGE_LATEST_ACCEPTED_ARTICLES_CAROUSEL_RENDER // "true"')
            export VITE_JOURNAL_HOMEPAGE_LAST_INFORMATION_RENDER_TYPE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_HOMEPAGE_LAST_INFORMATION_RENDER_TYPE // "last-news"')
            export VITE_JOURNAL_STATISTICS_ACCEPTANCE_RATE_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_ACCEPTANCE_RATE_RENDER // "true"')
            export VITE_JOURNAL_STATISTICS_NB_SUBMISSIONS_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_NB_SUBMISSIONS_RENDER // "true"')
            export VITE_JOURNAL_STATISTICS_NB_SUBMISSIONS_DETAILS_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_NB_SUBMISSIONS_DETAILS_RENDER // "true"')
            export VITE_JOURNAL_STATISTICS_REVIEWS_REQUESTED_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_REVIEWS_REQUESTED_RENDER // "true"')
            export VITE_JOURNAL_STATISTICS_REVIEWS_RECEIVED_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_REVIEWS_RECEIVED_RENDER // "true"')
            export VITE_JOURNAL_STATISTICS_MEDIAN_SUBMISSION_PUBLICATION_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_MEDIAN_SUBMISSION_PUBLICATION_RENDER // "true"')
            export VITE_JOURNAL_STATISTICS_MEDIAN_REVIEWS_NUMBER_RENDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_MEDIAN_REVIEWS_NUMBER_RENDER // "true"')
            export VITE_JOURNAL_STATISTICS_ACCEPTANCE_RATE_ORDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_ACCEPTANCE_RATE_ORDER // "1"')
            export VITE_JOURNAL_STATISTICS_NB_SUBMISSIONS_ORDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_NB_SUBMISSIONS_ORDER // "2"')
            export VITE_JOURNAL_STATISTICS_NB_SUBMISSIONS_DETAILS_ORDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_NB_SUBMISSIONS_DETAILS_ORDER // "3"')
            export VITE_JOURNAL_STATISTICS_REVIEWS_REQUESTED_ORDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_REVIEWS_REQUESTED_ORDER // "1"')
            export VITE_JOURNAL_STATISTICS_REVIEWS_RECEIVED_ORDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_REVIEWS_RECEIVED_ORDER // "2"')
            export VITE_JOURNAL_STATISTICS_MEDIAN_SUBMISSION_PUBLICATION_ORDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_MEDIAN_SUBMISSION_PUBLICATION_ORDER // "3"')
            export VITE_JOURNAL_STATISTICS_MEDIAN_REVIEWS_NUMBER_ORDER=$(echo "$CONFIG_VALUES" | jq -r '.VITE_JOURNAL_STATISTICS_MEDIAN_REVIEWS_NUMBER_ORDER // "4"')

            export VITE_EMAILS_SUFFIX=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EMAILS_SUFFIX // "@episciences.org"')
            export VITE_EPISCIENCES_HOMEPAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_HOMEPAGE // "https://www.episciences.org"')
            export VITE_EPISCIENCES_HOMEPAGE_FR=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_HOMEPAGE_FR // "https://www.episciences.org/fr/accueil"')
            export VITE_EPISCIENCES_JOURNALS_PAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_JOURNALS_PAGE // "https://www.episciences.org/journals"')
            export VITE_EPISCIENCES_JOURNALS_PAGE_FR=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_JOURNALS_PAGE_FR // "https://www.episciences.org/fr/revues"')
            export VITE_EPISCIENCES_DOCUMENTATION_PAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_DOCUMENTATION_PAGE // "https://doc.episciences.org"')
            export VITE_EPISCIENCES_DOCUMENTATION_PAGE_FR=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_DOCUMENTATION_PAGE_FR // "https://doc.episciences.org/fr"')
            export VITE_EPISCIENCES_ACKNOWLEDGEMENTS_PAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_ACKNOWLEDGEMENTS_PAGE // "https://www.episciences.org/partners"')
            export VITE_EPISCIENCES_ACKNOWLEDGEMENTS_PAGE_FR=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_ACKNOWLEDGEMENTS_PAGE_FR // "https://www.episciences.org/fr/partenaires"')
            export VITE_EPISCIENCES_LEGAL_TERMS_PAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_LEGAL_TERMS_PAGE // "https://www.episciences.org/legal-terms"')
            export VITE_EPISCIENCES_LEGAL_TERMS_PAGE_FR=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_LEGAL_TERMS_PAGE_FR // "https://www.episciences.org/fr/mentions-legales"')
            export VITE_EPISCIENCES_LEGAL_PRIVACY_STATEMENT_PAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_LEGAL_PRIVACY_STATEMENT_PAGE // "https://www.episciences.org/privacy-and-personal-data"')
            export VITE_EPISCIENCES_LEGAL_PRIVACY_STATEMENT_PAGE_FR=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_LEGAL_PRIVACY_STATEMENT_PAGE_FR // "https://www.episciences.org/fr/donnees-personnelles"')
            export VITE_EPISCIENCES_LEGAL_PRIVACY_TERMS_OF_USE_PAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_LEGAL_PRIVACY_TERMS_OF_USE_PAGE // "https://www.episciences.org/terms-of-use"')
            export VITE_EPISCIENCES_LEGAL_PRIVACY_TERMS_OF_USE_PAGE_FR=$(echo "$CONFIG_VALUES" | jq -r '.VITE_EPISCIENCES_LEGAL_PRIVACY_TERMS_OF_USE_PAGE_FR // "https://www.episciences.org/fr/cgu"')
            export VITE_ORCID_HOMEPAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_ORCID_HOMEPAGE // "https://orcid.org"')
            export VITE_DOI_HOMEPAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_DOI_HOMEPAGE // "https://doi.org"')
            export VITE_ZOTERO_HOMEPAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_ZOTERO_HOMEPAGE // "https://www.zotero.org"')
            export VITE_ARXIV_HOMEPAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_ARXIV_HOMEPAGE // "https://arxiv.org"')
            export VITE_CREATIVE_COMMONS_HOMEPAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_CREATIVE_COMMONS_HOMEPAGE // "https://creativecommons.org"')
            export VITE_ARCHIVE_SOFTWARE_HERITAGE_HOMEPAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_ARCHIVE_SOFTWARE_HERITAGE_HOMEPAGE // "https://archive.softwareheritage.org"')
            export VITE_HAL_HOMEPAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_HAL_HOMEPAGE // "https://hal.science"')
            export VITE_MATHJAX_HOMEPAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_MATHJAX_HOMEPAGE // "https://cdnjs.cloudflare.com/ajax/libs/mathjax"')
            export VITE_TWITTER_HOMEPAGE=$(echo "$CONFIG_VALUES" | jq -r '.VITE_TWITTER_HOMEPAGE // "https://twitter.com"')
          else
            echo "Configuration file not found; using only default variables."
          fi
